[package]
name = "crypto-scanner-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["ws"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shuttle-axum = "0.35"
shuttle-runtime = "0.35"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
tower-http = { version = "0.4", features = ["fs"] }
reqwest = { version = "0.11", features = ["json"] }
rig = "0.4"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
